### ISSUE TITLE
Fix: Release

### ISSUE THREAD

**Issue by claugp06** [3ralon/decide-single-zambrano#112]
Al realizar un merge de develop con main, nos hemos dado cuenta que el release.yml no funciona ya que no contiene unas tags indicadas:
<img width="422" alt="image" src="https://github.com/3ralon/decide-single-zambrano/assets/99924348/5ab033a0-a606-4bd1-8f02-4eeb36eb42b8">

 Nos disponemos a arregarlo.

**Comment by laurolmer** [comment]
Cerramos esta tarea porque no hacía falta crear una rama ni meter líneas de código nuevas para solucionarlo
