### ISSUE TITLE
Fix: comprobar census antes de votar

### ISSUE THREAD

**Issue by 3ralon** [3ralon/decide-single-zambrano#115]
**Describir el bug**
Trabajando en los tests del módulo de voting me di cuenta de que en las vistas del módulo booth no se hace la comprobación del censo para el usuario que intenta acceder para votar. Por lo que, en principio, podría acceder cualquier usuario.

**Para reproducir**
_No hay pasos para reproducir._

**Comportamiento esperado**
Lo que debería suceder es que la aplicación lanzase un **HTTP 401 Unauthorized** cada vez que un usuario intentase acceder a una votación sin estar dentro del listado del censo.

**Capturas de pantalla**
En esta captura del archivo _booth/views.py_ se puede ver como hay un comentario con **#TODO** que indica que no se está haciendo la comprobación. Posiblemente, un incremento que dejasen por hacer los owners del [repo original](https://github.com/EGCETSII/decide).

![image](https://github.com/3ralon/decide-single-zambrano/assets/128732971/b02e1b98-45cd-4b7b-b8bc-effa1b2c0dfa)

**Contenido adicional (Opcional)**
Para implementar esta feature, me gustaría llevar a cabo un **TDD** _(Test Driven Development_. De esta forma, primero, diseñaré e implementaré un test que deberá pasar la aplicación al implementar la funcionalidad.

En concreto, quiero proponer el desarrollo a mi compañera @laurolmer  ya que es la integrante con menos líneas de código hasta el momento.

**Comment by laurolmer** [comment]
Me parece correcto, muchas gracias. Comienza tú con el desarrollo del test y yo me encargo de la funcionalidad, por ejemplo.

**Comment by 3ralon** [comment]
Haciendo los tests, me he dado cuenta de que probablemente esta nueva funcionalidad afecte a los tests del módulo de voting. Así que voy a revisarlos y cambiarlos en esta rama ya que están asociados a la nueva característica.

@laurolmer

**Comment by laurolmer** [comment]
Me parece bien, tenemos tiempo así que podemos permitírnoslo. Avísame cuando termines para implementar mi parte, crack.
