### ISSUE TITLE
Fix: Voting Tests

### ISSUE THREAD

**Issue by laurolmer** [3ralon/decide-single-zambrano#56]
Soluciona los problemas con los tests del módulo voting. En concreto:

testExists: comprueba si existe una votación. Fallaba porque no se había creado dicha votación.

test_create_voting_API y test_create_voting_from_api: crean una votación mediante el uso de la API desarrollada por @silvglad. El problema consisitía en que al crearse se hace una comprobación de todos los campos de request.data de la petición. Si falta algún campo no crea la votación. Parece ser que se había actualizado el código de la vista, pero no los tests correspondientes.

test_ranking_voting: crea una votación de tipo ranking. El problema consistía en que no hallaba de forma correcta el valor del ranking más votado. Por ello, al comparar, el postprocesado y el tally no daban el mismo resultado.

**Comment by 3ralon** [comment]
Soluciona los problemas con los tests del módulo voting. En concreto:

testExists: comprueba si existe una votación. Fallaba porque no se había creado dicha votación.

test_create_voting_API y test_create_voting_from_api: crean una votación mediante el uso de la API desarrollada por @silvglad. El problema consisitía en que al crearse se hace una comprobación de todos los campos de request.data de la petición. Si falta algún campo no crea la votación. Parece ser que se había actualizado el código de la vista, pero no los tests correspondientes.

test_ranking_voting: crea una votación de tipo ranking. El problema consistía en que no hallaba de forma correcta el valor del ranking más votado. Por ello, al comparar, el postprocesado y el tally no daban el mismo resultado.

**Comment by 3ralon** [comment]
Ha habido que reabrir la issue porque me he dado cuenta de que la ordenación de las opciones de la votación ranking no estaba bien implementada. Por tanto, al arreglarlo, tenemos que modificar el test para que haga bien la comprobación.
