### ISSUE TITLE
Incidencia: Google Login en Docker

### ISSUE THREAD

**Issue by MarioArocaPaez** [3ralon/decide-single-zambrano#71]
Abro esta incidencia para comentaros un problema que está habiendo con la funcionalidad del Login y Register con Google. Esto a parte de con el código se gestiona dentro del Google Cloud Platform. En un apartado del proyecto tienes que añadir las urls que están permitidas para acceder a esta funcionalidad. Por ahora con el localhost va todo bien, pero el problema es que si le intentamos meter un enlace de Docker este no le gusta.
![imagen](https://github.com/3ralon/decide-single-zambrano/assets/73229438/6a4a8cee-ac96-4ef0-bbea-d7e6adc5b39f)
Ya que este se está esperando un dominio privado principal (localhost) o un enlace con dominio publico de nivel superior (.com y tal).
Lo bueno es que esto solo pasa con Docker, cuando despleguemos la aplicación en render esto si funcionará
![imagen](https://github.com/3ralon/decide-single-zambrano/assets/73229438/c0773536-c705-4d75-9329-6dae4e231726)
Lo que voy a hacer a partir de ahora es durante este fin de semana intentar buscar alguna solución para esto, el profesor me propuso una cosa y quizás puede funcionar. Si queréis ayudarme o encontráis cualquier info que resulte interesante me lo comentáis, aquí somos un equipo👊
Pero si para el domingo por la noche no tengo ninguna solución para este problema yo descartaría esta issue y tiraría para adelante aunque esto no funcione en Docker. Así que quiero que quede constancia de esto por aquí 👍

**Comment by MarioArocaPaez** [comment]
Chicos he estado este finde intentando encontrar alguna manera de hacer esto y no encuentro nada que realmente me sirva. Cierro esto por ahora ya que nos urgen otras cosas en el trabajo. Lo siento

**Comment by laurolmer** [comment]
No te preocupes compañero, hay más cosas que puedes hacer

**Comment by MarioArocaPaez** [comment]
Buenas a todos, reabro esta issue ya que después de la reunión de ayer con el profesor este me propuso una forma de hacer que esto funcione mediante el archivo hosts de ubuntu
https://pimylifeup.com/ubuntu-hosts-file/
Voy a seguir intentandolo un poco a ver si consigo que funcione esto :rocket:

**Comment by MarioArocaPaez** [comment]
Hola chicos, estuve hablando de esto con Claudia, ya que es ella quien ha hecho lo del docker. 
Al final resulta que ha sido un malentendido, ya que como ha configurado el docker se carga todo desde el host, por lo que cuando corremos la aplicación desde docker esta se ejecuta desde el host y no desde la red interna en la que se comunican los contenedores. Por lo tanto, correremos la aplicación en docker, pero seguirá siendo desde el localhost. Entonces, no habrá problema con que esto funcione, ya que un localhost se puede añadir al Google Cloud Platform sin problema. Doy esta incidencia como resuelta y cerrada.
