### ISSUE TITLE
Test: Tests de carga de census

### ISSUE THREAD

**Issue by claugp06** [3ralon/decide-single-zambrano#85]
Se quiere crear un test de carga usando locust para la función de exportar el csv ya que podría suceder picos en los que haya más uso de la aplicación.

**Comment by claugp06** [comment]
He intentando implementar un test de carga para la función de exportación de un csv pero me falla al inicio de sesión de un superuser (solo ellos pueden descargar el censo en formato csv) y por tanto no funciona. Si a alguno se le ocurre algo para hacerlo funcionar.

**Comment by laurolmer** [comment]
Voy a echarle un ojo

**Comment by claugp06** [comment]
He intentado averiguar el motivo de que no funcione ya que la dirección en principio del inicio de sesión es correcta y no he conseguido avanzar nada nuevo. @laurolmer ¿conseguistes tu avanzar algo?. Te pregunto por cerrar el issue y centrarnos en otras partes del proyecto.
