### ISSUE TITLE
Feat: Instalar linter en el proyecto

### ISSUE THREAD

**Issue by 3ralon** [3ralon/decide-single-zambrano#86]
De cara a que tengamos un código más sano y fácil de entender y siguiendo algunas recomendaciones de compañeros en las exposiciones de clase, se va a implementar la herramienta _pre-commit_ que realiza un escaneado del código y corrige este tipo de problemas aplicando reglas de estilos como las de black formatter.

**Comment by 3ralon** [comment]
Esta PR implementa un linter en el proyecto que se ejcutará en el momento previo al hacer commit. El funcionamiento y la configuración de dicha funcionalidad está explicada en la siguiente https://github.com/3ralon/decide-single-zambrano/discussions/87.

**Comment by MarioArocaPaez** [comment]
Reabro ya que voy a aplicar los cambios de Linter a todo el proyecto
