### ISSUE TITLE
Feat: Link authtentication con homepage

### ISSUE THREAD

**Issue by MarioArocaPaez** [3ralon/decide-single-zambrano#93]
Ahora mismo, en el módulo de autenticación, hay dos funcionalidades aisladas. En _authentication/register,_ tenemos la posibilidad de que los usuarios se registren sin ser administradores, y en _authentication/signin,_ tenemos la posibilidad de que los usuarios inicien sesión. Sin embargo, estos están ahora mismo completamente aislados del resto de la aplicación. Hago esta issue para enlazarlos con nuestra página de inicio.

**Comment by 3ralon** [comment]
Se cierra esta issue debido a que se ha creado por confusión. Esta feature ya está implementada en el proyecto.
